# Scraping top times in the women's 50 freestyle (long-course meter) across 2000-2026 seasons

# Notes:
#   USA Swimming has a private internal API so the scraper needs authentication with some custom headers
#   The server checks whether the user has an active logged-in session, so it requires session tokens to get data
#   Used httr2 documentation (httr2.r-lib.org) to navigate the req_ functions
#   Also found this guide useful: r-bloggers.com

### Source ###
# Data from USA Swimming Data Hub (data.usaswimming.org)
# Data Hub > Leaderboard > Top Times > search form: Best Times, Female, LCM, 50 FR, filter by season

# DevTools > Network tab > Fetch/XHR filter
#   Headers:
#       API endpoint: times-api.usaswimming.org/swims/TimesSearch/GetTopTimesLeaderBoard
#       Request Headers - copy device-id, usas-session-id, usas-sub-id, appname
#   Payload:
#       seasonKey: 17-41, 150, 155
#       eventId: 55
#       competitionGenderTypeId: 2


### Setup ###
# Packages used
library(tidyverse)
library(httr2)

# Live session tokens
# (session and sub id expire when browser session ends, so must be updated)
device_id
usas_session_id
usas_sub_id
appname <- "DataHub"

# Create folder for raw data
dir.create("data/raw", showWarnings=FALSE)


### Mapping season keys to years ###
# Note: in USA Swim website, keys are consecutive for 2000-2024 then switch for 2025, 2026
# Seasons denoted by the year they end in (e.g., the 2026 season runs from 9/1/2025-8/31/2026)
season_keys_df <- tibble(
  year_end = 2000:2024,
  season_key = 17:41
  ) |> 
  add_row(year_end = c(2025, 2026),
          season_key = c(150, 155))


### Scraper function ###
get_top_times <- function(season_key,
                          event_id = 55, # default to women's 50 FR LCM event code in USA Swimming database
                          gender_id = 2, # default to code for female swimmers in USA Swimming database
                          top_n = 40) {
  # Create request object targeting the below API endpoint 
  resp <- request(
    "https://times-api.usaswimming.org/swims/TimesSearch/GetTopTimesLeaderBoard"
    ) |> 
    
    # Set metadata headers to describe user (subset of the headers generated by DevTools)
    req_headers(
      "appname" = "DataHub",
      "device-id" = device_id,
      "usas-session-id" = usas_session_id,
      "usas-sub-id" = usas_sub_id
    ) |> 
    
    # Converts R list into JSON payload sent in the request body (core filter variables)
    req_body_json(list(
      eventId = event_id,
      competitionGenderTypeId = gender_id,
      seasonKey = season_key,
      bestTimesOnly = 1,
      loggedInUserClubs = FALSE, # include swimmers across all clubs
      teamUsaEligible = FALSE # include any swimmer competing in the U.S. regardless of citizenship
    )) |> 
    
    req_throttle(rate = 10 / 60) |> # limit scaper speed
    req_retry(max_tries = 3, backoff = ~10) |> 
    
    req_perform() |> # execute request and receive response object from server
    
    # read raw JSON text from server and convert to R data structures
    resp_body_json(simplifyVector = TRUE) |> 
    as_tibble() |> 
    
    slice_head(n = top_n) |> # keep only top_n times
    mutate(season_key = season_key) # add a metadata column containing season ID to each row
  
}

# Scrape across all seasons
raw_df <- season_keys_df$season_key |> 
  map(get_top_times) |> 
  list_rbind() |> 
  left_join(season_keys_df, by = "season_key")

# Save output
write_csv(raw_df, "data/raw/50fr_women_lcm_raw.csv")


